---
title: "Welcome to WhereIP"
date: "31 July 2016"
output: 
  html_document: 
    keep_md: yes
---


Hailing from Stone and Chalk in Sydney, we proudly present the outcome of two sleepless nights, sugar fueled days and too much junk food: 

## WhereIP

We wanted to understand where and how Australia's economic future is made.  
To this end we combined data sets from Department of Industry, Innovation and Science and from IP Australia. The result is an interactive website that lets you explore where Australia has been innovating over the last 6 years.

### Features
1. Zoom through our **Map** to see where the most patent applicants in particular fields are registered
2. Explore how areas have been trending, on the **Trends** tab
3. Check which factors drive innovation on the **Local Heroes** tab: It shows the which types of businesses are active and the number of professional qualifications in an area.

Use interactive features to explore and slice and dice the data to uncover pockets of innovation and areas of strength for future enterpreneurs to tap into. 


### Data sets used are: 

* [https://data.gov.au/dataset/sa3-region-innovation-data](SA3 Region Innovation Data 2009-15), accessed via their API
* [https://data.gov.au/dataset/intellectual-property-government-open-live-data](Intellectual Property Government Open Live Data)
* [www.wipo.int/export/sites/www/ipstats/en/statistics/patents/xls/ipc_technology.xls](WIPO.int IPC8-Technology Concordance)

